site_name: Axium Documentation
site_url: https://docs.axium.tools
site_description: Structure for your terminal
site_author: Axium Team
repo_url: https://github.com/axium-tools/axium
repo_name: axium-tools/axium
edit_uri: ""

theme:
  name: material
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
  icon:
    repo: fontawesome/brands/github

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [.]
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_root_full_path: false
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            members_order: source

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Concepts:
      - Environments: concepts/environments.md
      - Command Prefixes: concepts/prefixes.md
      - Spokes: concepts/spokes.md
      - Command Registry: concepts/registry.md
      - tmux Integration: concepts/tmux-integration.md
  - Guides:
      - Writing Spokes: guides/writing-spokes.md
  - Reference:
      - API Documentation:
          - Core: reference/api/core.md
          - CLI: reference/api/cli.md
          - Daemon: reference/api/daemon.md
          - Spokes: reference/api/spokes.md
          - Registry: reference/api/registry.md
  - Development:
      - Contributing: development/CONTRIBUTING.md
      - Style Guide: development/STYLE-GUIDE.md
      - Roadmap: development/ROADMAP.md
      - Claude Context: development/CLAUDE.md
      - AI Guidelines: development/AI_GUIDELINES.md
  - Examples:
      - Environments: examples/envs.yaml
      - Prefixes: examples/prefixes.yaml

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/axium-tools/axium
